### ISSUE TITLE
Feature request: debug and release versions in same build directory tree

### ISSUE THREAD

**Issue by JPGygax68** [ShiftMediaProject/FFmpeg#15]
When working closely with FFmpeg builds (read: when stepping into the code with the debugger becomes a habit), having to copy the generated DLLs and .pdb files becomes a source of errors. Currently, building any configuration deletes the output directories, so that you can't keep debug and release builds together without copying them.

**Comment by Sibras** [comment]
Im not sure I understand the issue correctly, when you say the output directories are deleted which ones are you referring to? Currently a build should only delete any previously installed header files to make sure there aren't any left over from a previous version. But the lib and bin directories should remain completely untouched. Since the Debug and Release builds have different naming then the outputs shouldn't overlap so you might have to elaborate on what you mean.

PS. thanks for the donation.

**Comment by JPGygax68** [comment]
Sorry, that was my mistake. The debug builds do have an appended 'd', 
and that's exactly what I need. Not sure what happened earlier, but I 
have them both in the same directory now, as they should be.
