### ISSUE TITLE
Question: reducing reserved stack size

### ISSUE THREAD

**Issue by JPGygax68** [ShiftMediaProject/FFmpeg#16]
This is not a bug, and it may have nothing to do with FFmpeg. Nevertheless, I'd appreciate any input on this problem.

Our application, which is 32-bit, requires quite a bit of memory. However, it's not its needs of physical memory (those are below 1GB) that present the problem, but the fact that the per-process 2GB address space is exhausted.

I was able to determine this using Mark Russinovich's excellent VMMap tool. VMMap also showed me that a lot of the address space is being wasted on the stacks: roughly 500MB are reserved for the stacks of 12 threads - only 5MB being actually used (both numbers are totals over all threads). It's quite probable that the actual consumption would have gone up a bit if the creation of the video stream had succeeded (which it didn't because memory allocation failed), but I suspect the actual need is nowhere near as high as the reserved amounts.

I'm not sure why our exe is reserving that much stack; it might be because of a VS project setting that I can't check myself at the moment. But if it turns out, as I think is the case, that we do need a lot of stack for the main thread, is there a way to set a specific stack size for the threads created by FFmpeg ?

**Comment by Sibras** [comment]
The VS projects settings to control stack allocation are are found in the "Linker->System" section of the project properties (in this case it would be the x264 project). However by default only 1MB is allocated for the stack of each thread so 500MB seems a bit high. It is possible to programmatically control the stack allocation at thread creation time using CreateThread however none of the supplied projects use this method and just use the default project settings.

Using a standard x264 build should work fine on 32b and when doing an encode most of the new threads will be created by libx264 internally so you can try testing it using the direct x264 cli program found in the supplied repo. I will mention that when doing 10bit encodes the upstream project doesnt even support using 32bit due to memory space issues causing it to fail. That said a default 8bit encode should still function.

**Comment by JPGygax68** [comment]
Thanks Matt! I've have another look and trying to create the .h264 video stream makes the stack address space grow from ~450MB to ~570MB. That's a significant jump, but it's hardly the root cause of our problems. On the other hand, we have a "Private Data" segment 1GB in size, that's probably where we should investigate.
