### ISSUE TITLE
Unresolved external symbols in debug builds

### ISSUE THREAD

**Issue by Sibras** [ShiftMediaProject/FFmpeg#2]
Due to dead code elimination being extensively used throughout FFmpeg code optimisation needs to be enabled in order to remove to dead function calls. Unfortunately this optimisation is not performed in debug builds and so many unresolved external symbols appear. Currently the linker is forced to ignore these symbols but this is a rather dirty hack. Need to find more elegant way to handle this.

**Comment by JPGygax68** [comment]
I'm linking the statically built FFMPEG libraries into my DLL, but I cannot seem to resolve this issue using `/force:unresolved` as mentioned in the readme.  I'm still getting a very (>2k) number of unresolveds, starting with `_ff_async_protocol`.

Curiously, that function is defined in a file named `async.c`, which is present in the sources but not included in the list of Source Files of the `libavformat` project.

What am I missing?

**Comment by Sibras** [comment]
async.c not being included is standard behaviour as it doesnt build natively with msvc so nothing to worry about there.

The main thing is that /force:unresolved doesnt stop the linker from spewing out heaps of errors and stating that the link failed. It should however still allow the linker to output a completed binary. So providing that the linker option is added correctly you should still actually get a working output DLL and all the errors listed by the linker can be entirely ignored.

So you should be able to do a manual build, ignore the link error output but then debug the DLL as normal (as long as nothing tries to rebuild the DLL on debug execution).

This is not the cleanest solution but FFmpeg was not written with msvc debugging in mind and the upstream code is not going to be completely rewritten to fix this any time soon.

**Comment by JPGygax68** [comment]
You are right! The DLL *is* being generated.

Visual Studio is evidently unaware of this, as it is trying to rebuild and asking me whether I want to "run the last successful build" - but it appears to work nonetheless.

Ouf of curiosity, what functionality is getting lost because of the missing `async.c` ?

**Comment by Sibras** [comment]
It just does url streaming by wrapping it in an async background thread.

There have been several components in FFmpeg that ive converted to run on windows natively. There are a couple more ive missed (async and decklink being the only remaining ones) but unless there actually used by someone I dont normally here about them.

**Comment by JPGygax68** [comment]
Thanks!

I've resolved my original issue thanks to your libraries.

(Of course I've run into a new one - hopefully I won't have to bother 
you about that... :-) )

**Comment by JPGygax68** [comment]
One other thing. I'm using your project for paid work, so I'd like to make a small donation. Would you consider subscribing to Pledgie ? (see https://github.com/blog/57-getting-paid-the-open-source-way)

**Comment by Sibras** [comment]
Certainly, any donation would be much appreciated.
I have started a pledgie campaign here "http://pledgie.com/campaigns/30265" and ill soon update the project pages with proper links.
<a href='https://pledgie.com/campaigns/30265'><img alt='Click here to lend your support to: Shift Media Project and make a donation at pledgie.com !' src='https://pledgie.com/campaigns/30265.png?skin_name=chrome' border='0' ></a>

PS. I have also fixed async and decklink so they work without needing pthreads which should be available once I push them to upstream.

**Comment by JPGygax68** [comment]
Donation made!

And thanks for your continued work.

**Comment by Sibras** [comment]
thank you in return.

**Comment by xuws20** [comment]
when run bat file，
Error: Failed calling temp.bat. Ensure you have Visual Studio or the Microsoft compiler installed and that any required dependencies are available.

**Comment by Sibras** [comment]
That is a completely different issue to this one.
That error is for the project generator which is not included in this repo at all. If you are trying to run one of the project_generate scripts contained in this repo then youll find you probably dont actually need to as the projects have already been generated.
If you are trying to generate new projects using the generator with different configuration then that error belongs in a new ticket in the FFVS-Project-Generator repo.
However before that just check the output log the project_generator.exe creates in its bin folder as that will have the exact error. As for fixing it, make sure you have performed the appropriate required steps that are outlined in the readme.txt file.

**Comment by xuws20** [comment]
1>             These errors are the result of dead code elimination not being performed in debug builds.
1>libavdeviced.lib(SDL_error.obj) : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification
1>     Creating library D:\tmp\ffmpeg\ffmpeg\ffmpeg_vs2013\ffmpeg\SMP\..\..\..\msvc\ffmpeg.lib and object D:\tmp\ffmpeg\ffmpeg\ffmpeg_vs2013\ffmpeg\SMP\..\..\..\msvc\ffmpeg.exp
1>cmdutils.obj : error LNK2019: unresolved external symbol _avresample_version referenced in function _print_all_libs_info
1>cmdutils.obj : error LNK2019: unresolved external symbol _avresample_configuration referenced in function _print_all_libs_info
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_alsa_muxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_alsa_demuxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_avfoundation_demuxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_bktr_demuxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_caca_muxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_decklink_muxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_decklink_demuxer
1>libavdeviced.lib(alldevices.obj) : error LNK2001: unresolved external symbol _ff_dv1394_demuxer

**Comment by xuws20** [comment]
thanks,in dubug mode, set  Undefined Symbol Only (/FORCE:UNRESOLVED) ffmpeg.exe is output.but run ffmpeg -h, program crash.

**Comment by Sibras** [comment]
Im unable to reproduce this problem as a fresh build on ffmpeg in debug worked perfectly fine for me. You ll have to provide additional information in order to reproduce.

**Comment by xuws20** [comment]
1 in compile，remove files about cuda，opencl。
2 the image of crash is :
//ffmpeg_vs2013\ffmpeg\libavcodec\utils.c
av_cold void avcodec_register(AVCodec *codec)
{
    AVCodec **p;
    avcodec_init();
    p = last_avcodec;
    codec->next = NULL;//crash position

    while(*p || avpriv_atomic_ptr_cas((void * volatile *)p, NULL, codec))
        p = &(*p)->next;
    last_avcodec = &codec->next;

    if (codec->init_static_data)
        codec->init_static_data(codec);
}

**Comment by xuws20** [comment]
thanks.delete option about nv opengl,generate,rebuild。ffmpeg.exe can run sucessfully.
