### ISSUE TITLE
/MD vs2015 runtime, /MT?

### ISSUE THREAD

**Issue by dbyoung720** [ShiftMediaProject/FFmpeg#32]
## Context

The compile type is /MD, so it carries the VS2015 runtime, 
and we can't guarantee that the clients are installed.
If you could just change it to /MT.

## Expected Behavior

change to /MT.

**Comment by Sibras** [comment]
This one is not likely to be changed. Originally the projects used /MT but they were changed to /MD as when linking in multiple libraries /MT can cause issues due to multiple different instantiations of the runtime (memory functions are the main culprit). So /MD is used as it performs better. Also most applications linking in the libs/dlls are generally built using /MD and mixing in different runtimes is a bad idea so the libs/dlls are made to match the common applications /MD.

It is recommended to use /MD. Most people just bundle the redistributable with there applications and auto install it at the same time. If you absolutely must use /MT then just change the corresponding setting in the Visual Studio projects and recompile it yourself.

**Comment by kamisBB** [comment]
I use vs2015， I change the corresponding setting in the Visual Studio projects with  /MT（all project，i check multiple times）， when recompile the project， there had problem：

5>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)
5>libavcodec.lib(api.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libavfilter.lib(main.obj) 中)

**Comment by Sibras** [comment]
Well I dont speak whatever '检测到' is, so it s a bit hard to debug an error thats in another language. In future make sure error messages are in english when asking for support.

Anyway the error appears to be because api.c from the avcodec project and main.c from the libavfilter project are compiled using different runtime configurations. i.e. Not all files have been compiled with /MT. Clean all projects and force a rebuild. If that still doesnt work then you clearly havnt vhanged all projects to /MT.

**Comment by kamisBB** [comment]
thanks， i finish this problem,   I delete the  ./FFmpeg/SWP/obj   duration  and rebuild
