### ISSUE TITLE
ffplay cause sdl error

### ISSUE THREAD

**Issue by tifentan** [ShiftMediaProject/FFmpeg#33]
when i do `ffplay -i rtmp://xxxxxxxx ` to play a rtmp live stream,it seems sdl_init error ！！
## Context
`ffplay -i rtmp://xxxxxxxx `

![qq 20180308153330](https://user-images.githubusercontent.com/24734576/37138742-36152be6-22e6-11e8-8fac-54657871b052.png)

## Your Environment

* Version Used: lastest
* Operating System and Version: win7
* Compiler and Version(s): vs2015

## Possible Fix

sdl init error

**Comment by Sibras** [comment]
Since it appears you are compiling the source code yourself you will have to list what version of sdl you are linking against and what version of ffmpeg source you are using.

You may also want to try the precompiled versions supplied on this projects release page and see if they also display the same issue (try a few different versions as that may help identify an introduction of a regression).

As for your open audio failure youll need to see issue #26 for further information.

**Comment by Sibras** [comment]
I have applied a fix to the upstream ffmpeg project that fixes this issue. This fix is now also available in the most recent code hosted on this site aswell.
