### ISSUE TITLE
ffmpeg is slower than one from zeranoe.

### ISSUE THREAD

**Issue by JiaLinQuan** [ShiftMediaProject/FFmpeg#36]
I had some tests with ffmpeg binaries from shiftmedia and zeranoe.

- ffmpeg-3.4.2-win64-shared.zip (zeranoe)
https://ffmpeg.zeranoe.com/builds/win64/shared/
- 3.4.2.r90885 (shiftmedia)
https://github.com/ShiftMediaProject/FFmpeg/releases

Here are test commands and results.

1.  ffmpeg -buildconf

-  zeranoe
![zeranoe_buildconf](https://user-images.githubusercontent.com/25911216/39497855-b7c336d0-4dd7-11e8-8e81-2c0f0dcf3851.png)

-  shiftmedia
![image](https://user-images.githubusercontent.com/25911216/39497886-d63f9734-4dd7-11e8-91c6-9cacef85c71e.png)

2.  ffmpeg -i song.mp4 -vcodec mpeg4 -an -threads 6 output.mp4 (with and without -threads option, zeranoe is faster in every case..)
- zeranoe
![image](https://user-images.githubusercontent.com/25911216/39498038-855efe4e-4dd8-11e8-92ad-baf5e606aaa5.png)

- shiftmedia 
![image](https://user-images.githubusercontent.com/25911216/39498078-c7479c26-4dd8-11e8-91a9-3bbea519151b.png)

Above results shows that 
- two binaries are built with different config options and compilers.
- shiftmedia ffmpeg is slower than zeranoe`s.

I want to know correct reason what makes it slower.
- Which config option makes slower?
- FFmpeg built in msvc is slower than one built in gcc compiler?

Please check and let me know your ideas.

Thanks!

**Comment by Sibras** [comment]
This is most likely due to the internal mpeg4 encoder in FFmpeg being rather old and so it still includes inline mmx asm code that is only supported by certain versions of gcc. There are only a few places in FFmpeg that still have some old inline asm as most of the new work uses yasm/nasm, with mpeg4 being the main one that still has some left over. 

So some of the mpeg4 code is just old and unsupported with msvc. All newer encoders don't show this kind of difference and most people don't use the internal mpeg4 encoder in favor of xvid instead anyway.

**Comment by JiaLinQuan** [comment]
Great, thanks for your comments!

I am not sure that It is good to post this...
I need the ffmpeg libray (including ffmpeg application) for android.
I have one android app which uses ffmpeg.so for video processing by executing ffmpeg commands and it works well but converting speed is terribly slow so need to update ffmpeg.so.
I want to get that built for various cpu arch in android, neon, libx264 config options enabled for fastest video processing.
Any other options based your experiences is much acceptable.


Please contact me(skype address: live:jialin1982) if you can help me and price for that.
Thanks.
