### ISSUE TITLE
compile with decklink

### ISSUE THREAD

**Issue by syzby** [ShiftMediaProject/FFmpeg#39]
Hi, can you add "--enable-nonfree and --enable-decklink" to support bmd devices?

**Comment by Sibras** [comment]
Since decklink requires enabling nonfree which makes it non-redistributable then for legal reasons I wont be providing binaries built using that option. However you can create your own local project using the Visual Studio generator ([https://github.com/ShiftMediaProject/FFVS-Project-Generator](https://github.com/ShiftMediaProject/FFVS-Project-Generator)) which you can pass whatever settings you want and does support using decklink.

**Comment by syzby** [comment]
Thank you !!!
