### ISSUE TITLE
Useful to have separate directories for separate builds

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/FFmpeg#48]
Now we get all outputted to "msvc".  Useful to have separate directories for each configuration.

The important variables - other than platform (already take care)
- $(Configuration)
- $(PlatformToolset)

like - msvc-v141\Debug\x86

**Comment by Sibras** [comment]
Theres already subfolders for architecture and debug builds are differentiated by a 'd' suffix. Which is a reasonably standard layout so thats unlikely to change.

As for having a separate platform toolset folder It was assumed that most people wouldnt be mixing different compiler versions and so it wouldn't be necessary. Although it may be something I look into at a later date. Since v140/v141/v142 platform toolsets are compatible with each other its also possible to mix them without issue so separating toolsets wasnt deemed very important.

That said its really quick and easy for a user to just change the OutputDirectory if they wish a different folder structure.

**Comment by mediabuff** [comment]
Thanks. Although ‘d’ Doesn’t capture all possible configurations- static , dynamic etc

**Comment by Sibras** [comment]
Static builds have a lib prefix whereas dynamic builds do not e.g. libavcodec.lib is the static build avcodec.lib is the dynamic build.
