### ISSUE TITLE
very slow speed h265 to h264

### ISSUE THREAD

**Issue by dbyoung720** [ShiftMediaProject/FFmpeg#49]
## Context

 I compile SMP ok,  test h265 to 264
ffmpeg.exe  -hide_banner -y -noautorotate -i TEST.mkv -c:v h264_nvenc -profile:v main -level:v 4.2 -pix_fmt yuv420p -rc vbr -cq 22 -qmin 5 -qmax 30 -g 250 -filter_complex [0:0]null[VA];[0:4]scale=1920:1080[sub1];[VA][sub1]overlay=main_w/2-overlay_w/2:main_h-overlay_h[VIDEO] -map [VIDEO] -c:a aac -b:a 128k -ar 44100 -ac 2 -map 0:2 -metadata:s:a:0 language=zho -f mp4 -map_chapters -1 -metadata "title=aaa" -metadata artist=bbb -metadata genre=ccc -metadata "comment=ddd" TEST.mp4
speed is 0.5 --- 1.0

if use zeranoe ffmpeg.exe
speed is 4.5 --- 5.0

Both use GPU acceleration
But I don't know why your ffmpeg.exe is so slow.

## Your Environment

* Version Used: NEWEST
* Operating System and Version:  Windows10 X64
* Compiler and Version(s): VS2017

**Comment by Sibras** [comment]
There are a couple of locations in ffmpeg that use old inline assembly that is not standards compliant and cant be compiled by visual studio which can cause performance differences due to using different code paths. Most of this non-standard code has been replaced by better alternatives however there are still 1 or 2 locations that still exist.

At a guess i would suspect that the slowdown you are seeing is due to the old swscale code used for scaling in your filter complex. Since your using nvenc for encoding perhaps use the cuvid decoder that has inbuilt scaling and bypass the use of swscale altogether.
